### ISSUE TITLE
Request for updated input files

### ISSUE THREAD

**Issue by dzy-582** [UU-Hydro/DYNQUAL#2]
dear author,
    I am trying to do some exploratory research with this model. But i notice discrepancies between the input files online (https://opendap.4tu.nl/thredds/catalog/data2/pcrglobwb/catalog.htmland) and the initial configuration settings of the current model. Is it possible to get the updated input files and  any additional configuration details?
    Thank you very much

**Comment by edwinkost** [comment]
Not sure what you meant by 'discrepancies'. 

Yet, if you want to have a newer version of input files, you can check this https://geo.public.data.uu.nl/vault-pcrglobwb-cmip6/research-pcrglobwb-cmip6%5B1690540205%5D/original/hypflowsci6_v1.0/input_and_code/

https://public.yoda.uu.nl/geo/UU01/YM7A5H.html
